service: drift-base-lambda



plugins:
  - serverless-wsgi
  - serverless-python-requirements
custom:
  wsgi:
    #app: api.app
    #app: drift.uwsgiboot.app
    #app: drift.devapp.app
    app: drift.serverless.app
    # app: apitest.app
    packRequirements: false
  pythonRequirements:
    #dockerImage: drift-base:latest
    #usePipenv: true
    dockerizePip: true
    dockerFile: Dockerfile
    #dockerImage: drift-base:latest



provider:

  resourcePolicy:
    - Effect: Deny
      Principal: "*"
      Action: execute-api:Invoke
      Resource:
        - execute-api:/*/*/*
      Condition:
        StringNotEquals:
          "aws:sourceVpc": vpc-6458d901
    - Effect: Allow
      Principal: "*"
      Action: execute-api:Invoke
      Resource:
        - execute-api:/*/*/*


# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#

  name: aws
  runtime: python3.6
  stage: main                     # TEMPLATIZED
  stackName: DEVNORTH-drift-base-lambda      # TEMPLATIZED
  region: eu-west-1                   # TEMPLATIZED
  timeout: 10  # The default is 6 seconds. Note: API Gateway current maximum is 30 seconds
  deploymentBucket:
    name: serverless-devnorth # TEMPLATIZED
  vpc:
    securityGroupIds:
      - sg-ce4849ab                   # TEMPLATIZED
    subnetIds:
      - subnet-aef280cb               # TEMPLATIZED
      - subnet-8544def2               # TEMPLATIZED

  environment: # Service wide environment variables
    DRIFT_TIER: DEVNORTH                                                        # TEMPLATIZED
    DRIFT_CONFIG_URL: redis://redis.devnorth.dg-api.com:6379/0?prefix=dgnorth   # TEMPLATIZED

  tags:                               # TEMPLATIZED
      tier: DEVNORTH
      service-name: drift-base
      service-type: web-app
      Name: DEVNORTH-drift-base-api

  # API Gateway
  apiName: DEVNORTH-drift-base-api # TEMPLATIZED
  endpointType: private



functions:
  app:
    handler: wsgi.handler
    name: DEVNORTH-drift-base-lambda-main-app  # TEMPLATIZED
    events:
#      - http:
#          path: /
#          method: any
      - http: ANY /
      - http: 'ANY {proxy+}'
