service: drift-base-lambda

plugins:
  - serverless-wsgi
  - serverless-python-requirements
custom:
  wsgi:
    #app: api.app
    #app: drift.uwsgiboot.app
    #app: drift.devapp.app
    app: drift.serverless.app
    # app: apitest.app
    packRequirements: false
  pythonRequirements:
    #dockerImage: drift-base:latest
    usePipenv: true
    dockerizePip: true
    dockerFile: Dockerfile

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: eu-west-1
  vpc:
    securityGroupIds:
      - sg-ce4849ab
    subnetIds:
      - subnet-aef280cb
      - subnet-8544def2

  environment: # Service wide environment variables
    DRIFT_TIER: DEVNORTH
    DRIFT_CONFIG_URL: redis://redis.devnorth.dg-api.com:6379/0?prefix=dgnorth
    #FLASK_ENV: development
    #FLASK_DEBUG: true

  tags:
      tier: DEVNORTH
      service-name: drift-base
      service-type: web
      Name: DEVNORTH-drift-base

functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'